"""add requested event

Revision ID: 1b49db4be9e8
Revises: ca11d9c8cec0
Create Date: 2026-07-24 20:55:42.222112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b49db4be9e8'
down_revision: Union[str, Sequence[str], None] = 'ca11d9c8cec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE operation_event_type ADD VALUE IF NOT EXISTS 'REQUESTED';"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
