"""create operations table

Revision ID: 1f879030c5f9
Revises: 
Create Date: 2026-07-24 12:03:11.154402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f879030c5f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('RUB', 'USD', 'EUR', name='currency'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PROCESSING', 'COMPLETED', 'REJECTED', name='operation_status'), nullable=False),
    sa.Column('provider', sa.Enum('PROVIDER_SIMULATOR', 'TINKOFF', 'SBER', name='operation_provider'), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='check_operation_amount_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_payment_id')
    )
    op.create_index('ix_operations_created_at', 'operations', ['created_at'], unique=False)
    op.create_index('ix_operations_provider', 'operations', ['provider'], unique=False)
    op.create_index('ix_operations_status', 'operations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_operations_status', table_name='operations')
    op.drop_index('ix_operations_provider', table_name='operations')
    op.drop_index('ix_operations_created_at', table_name='operations')
    op.drop_table('operations')
    # ### end Alembic commands ###
