"""add to operation_event column  processead_at

Revision ID: 4a787ba1ff48
Revises: 1b49db4be9e8
Create Date: 2026-07-24 22:17:02.513695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a787ba1ff48'
down_revision: Union[str, Sequence[str], None] = '1b49db4be9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation_events', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operation_events', 'processed_at')
    # ### end Alembic commands ###
