"""add SEND_FAILED to event type

Revision ID: 8168900066b0
Revises: fce942cc352e
Create Date: 2026-07-28 13:48:49.773867

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8168900066b0"
down_revision: Union[str, Sequence[str], None] = "fce942cc352e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE operation_event_type ADD VALUE IF NOT EXISTS 'SEND_FAILED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
