"""add operation_id to operations

Revision ID: ca11d9c8cec0
Revises: ffb786692ff4
Create Date: 2026-07-24 15:01:20.425778

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ca11d9c8cec0"
down_revision: Union[str, Sequence[str], None] = "ffb786692ff4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "operations", sa.Column("operation_id", sa.String(length=255), nullable=False)
    )
    op.create_unique_constraint(None, "operations", ["operation_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "operations", type_="unique")
    op.drop_column("operations", "operation_id")
    # ### end Alembic commands ###
