"""add ignored event type

Revision ID: fce942cc352e
Revises: c151dc1ebceb
Create Date: 2026-07-28 13:47:08.207867

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fce942cc352e"
down_revision: Union[str, Sequence[str], None] = "c151dc1ebceb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE operation_event_type ADD VALUE IF NOT EXISTS 'IGNORED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
