"""create operation_event table

Revision ID: ffb786692ff4
Revises: 1f879030c5f9
Create Date: 2026-07-24 12:52:44.516206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ffb786692ff4'
down_revision: Union[str, Sequence[str], None] = '1f879030c5f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('CREATED', 'SENT_TO_PROVIDER', 'SUCCESS_FROM_PROVIDER', 'FAIL_FROM_PROVIDER', 'COMPLETED', name='operation_event_type'), nullable=False),
    sa.Column('from_status',
            postgresql.ENUM(
                            'CREATED',
                            'PROCESSING',
                            'COMPLETED',
                            'REJECTED',
                            name='operation_status',
                            create_type=False,
                        ),
                        nullable=True,
                    ),

    sa.Column('to_status',
            postgresql.ENUM(
                            'CREATED',
                            'PROCESSING',
                            'COMPLETED',
                            'REJECTED',
                            name='operation_status',
                            create_type=False,
                        ),
                        nullable=False,
                    ),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id', 'sequence_number', name='uq_operation_event_sequence')
    )
    op.create_index('ix_operation_events_created_at', 'operation_events', ['created_at'], unique=False)
    op.create_index('ix_operation_events_operation_id', 'operation_events', ['operation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_operation_events_operation_id', table_name='operation_events')
    op.drop_index('ix_operation_events_created_at', table_name='operation_events')
    op.drop_table('operation_events')
    # ### end Alembic commands ###
